<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en" />
	<meta name="robots" content="noindex,nofollow" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/css/admin/reset.css" /> <!-- RESET -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/css/admin/main.css" /> <!-- MAIN STYLE SHEET -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/css/admin/2col.css" title="2col" /> <!-- DEFAULT: 2 COLUMNS -->
	<link rel="alternate stylesheet" media="screen,projection" type="text/css" href="/css/admin/1col.css" title="1col" /> <!-- ALTERNATE: 1 COLUMN -->
	<!--[if lte IE 6]><link rel="stylesheet" media="screen,projection" type="text/css" href="css/main-ie6.css" /><![endif]--> <!-- MSIE6 -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/css/admin/style.css" /> <!-- GRAPHIC THEME -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/css/admin/mystyle.css" /> <!-- WRITE YOUR CSS CODE HERE -->
	<title>Excen Admin</title>
</head>

<body>

<div id="main">

	<!-- Tray -->
	<div id="tray" class="box">

		<p class="f-left box">


		</p>

		<p class="f-right">Gebruiker: <strong><a href="#">Administrator</a></strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><a href="#" id="logout">Uitloggen</a></strong></p>

	</div> <!--  /tray -->

	<hr class="noscreen" />

	<!-- Menu -->
	<div id="menu" class="box">
		<ul class="box">
			<li id="menu-active"><a href="#"><span>Dashboard</span></a></li> <!-- Active -->
			<li><a href="#"><span>Statistieken</span></a></li>
		</ul>

	</div> <!-- /header -->

	<hr class="noscreen" />

	<!-- Columns -->
	<div id="cols" class="box">

		<!-- Aside (Left Column) -->
		<div id="aside" class="box">

			<div class="padding box">
                            left
			</div>
                    <!-- /padding -->

		</div> <!-- /aside -->

		<hr class="noscreen" />

		<!-- Content (Right Column) -->
		<div id="content" class="box">
                    FGFDGDF<br/>
                     FGFDGDF<br/>
                      FGFDGDF<br/>
                       FGFDGDF<br/>
                        FGFDGDF<br/>
                         FGFDGDF<br/>
                          FGFDGDF<br/>
                           FGFDGDF<br/>
                            FGFDGDF<br/>
                             FGFDGDF<br/>
                              FGFDGDF<br/>
                               FGFDGDF<br/>
                                FGFDGDF<br/>
                                 FGFDGDF<br/>
                                  FGFDGDF<br/>
                                   FGFDGDF<br/>
                                    FGFDGDF<br/>
                                     FGFDGDF<br/>
                                      FGFDGDF<br/>
                                       FGFDGDF<br/>
                                        FGFDGDF<br/>
                                         FGFDGDF<br/>
                                         
		</div> <!-- /content -->

	</div> <!-- /cols -->

	<hr class="noscreen" />

	<!-- Footer -->
	<div id="footer" class="box">

		<p class="f-left">Copyright 2000-2011 Excen B.V.</p>

		<p class="f-right"></p>

	</div> <!-- /footer -->

</div> <!-- /main -->

</body>
</html>