<?php
echo $this->countrycode('0031');
?>
<?php echo __('transtest')?>
index

<br/>
<br/>
<div id="logged-in-as">
    <?php echo $this->loggedInAs(); ?>
</div>
<br/><br/>
<div id="content">
    <div id="mcontent">
        <!-- Defining Header for content section -->
        <header>
            <h2>About US</h2>

        </header>
        <!-- Defining Content Section -->
        <section>
            <!-- Defining content section article -->
            <article class="bpage">
                <div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin euismod tellus eu orci imperdiet nec rutrum lacus blandit. Cras enim nibh, sodales ultricies elementum vel, fermentum id tellus. Proin metus odio, ultricies eu pharetra dictum, laoreet id odio. Curabitur in odio augue. Morbi congue auctor interdum. Phasellus sit amet metus justo. Phasellus vitae tellus orci, at elementum ipsum. In in quam eget diam adipiscing condimentum. Maecenas gravida diam vitae nisi convallis vulputate quis sit amet nibh. Nullam ut velit tortor. Curabitur ut elit id nisl volutpat consectetur ac ac lorem. Quisque non elit et elit lacinia lobortis nec a velit. Sed ac nisl sed enim consequat porttitor.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin euismod tellus eu orci imperdiet nec rutrum lacus blandit. Cras enim nibh, sodales ultricies elementum vel, fermentum id tellus. Proin metus odio, ultricies eu pharetra dictum, laoreet id odio. Curabitur in odio augue. Morbi congue auctor interdum. Phasellus sit amet metus justo. Phasellus vitae tellus orci, at elementum ipsum. In in quam eget diam adipiscing condimentum. Maecenas gravida diam vitae nisi convallis vulputate quis sit amet nibh. Nullam ut velit tortor. Curabitur ut elit id nisl volutpat consectetur ac ac lorem. Quisque non elit et elit lacinia lobortis nec a velit. Sed ac nisl sed enim consequat porttitor.</p>
                </div>
                <div class="image">
                </div>
            </article>
        </section>
    </div>
    <!-- Defining Sidebar / Aside -->
    <aside>
        <section>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Feedback</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </section>
        <section>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Feedback</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </section>
        <section>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Feedback</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </section>
    </aside>
</div>
