
<!-- google fonts -->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:light&v1'
rel='stylesheet' type='text/css' />

<style type="text/css">
    /*--------------------------google fonts-----------------------------*/
    .googlefonts{
       font-family: 'Open Sans';
       font-style: normal;
       font-weight: 900;
    }
/*-----------------------knop die schaalt als de text grote wordt-------------------*/
clear {
    overflow: hidden;
    width: 100%;
}

a {
    color: #CC0088;
}

a.button {
    background: url("/images/bg_button_a.gif") no-repeat scroll right top transparent;
    color: #444444;
    display: block;
    float: left;
    font: 12px arial,sans-serif;
    height: 24px;
    margin-right: 6px;
    padding-right: 18px;
    text-decoration: none;
}

a.button span {
    background: url("/images/bg_button_span.gif") no-repeat scroll 0 0 transparent;
    display: block;
    line-height: 14px;
    padding: 5px 0 5px 18px;
}
a.button:active {
    background-position: bottom right;
    color: #000;
    outline: none; /* hide dotted outline in Firefox */
}
a.button:active span {
    background-position: bottom left;
    padding: 6px 0 4px 18px; /* push text down 1px */
}


/*-------------------  flag----------------------*/

.flagicon
{
    display:inline-block;
    width:16px;
    height:11px;
    background-image:url(/images/flags.png);
    background-position:-112px -264px;
    margin-top: 4px;
}

.flag_ad
{
    background-position:0px 0px;
}

.flag_ae
{
    background-position:-16px 0px;
}

.flag_af
{
    background-position:-32px 0px;
}

.flag_ag
{
    background-position:-48px 0px;
}

.flag_ai
{
    background-position:-64px 0px;
}

.flag_al
{
    background-position:-80px 0px;
}

.flag_am
{
    background-position:-96px 0px;
}

.flag_an
{
    background-position:-112px 0px;
}

.flag_ao
{
    background-position:-128px 0px;
}

.flag_ar
{
    background-position:-144px 0px;
}

.flag_as
{
    background-position:0px -11px;
}

.flag_at
{
    background-position:-16px -11px;
}

.flag_au
{
    background-position:-32px -11px;
}

.flag_aw
{
    background-position:-48px -11px;
}

.flag_ax
{
    background-position:-64px -11px;
}

.flag_az
{
    background-position:-80px -11px;
}

.flag_ba
{
    background-position:-96px -11px;
}

.flag_bb
{
    background-position:-112px -11px;
}

.flag_bd
{
    background-position:-128px -11px;
}

.flag_be
{
    background-position:-144px -11px;
}

.flag_bf
{
    background-position:0px -22px;
}

.flag_bg
{
    background-position:-16px -22px;
}

.flag_bh
{
    background-position:-32px -22px;
}

.flag_bi
{
    background-position:-48px -22px;
}

.flag_bj
{
    background-position:-64px -22px;
}

.flag_bm
{
    background-position:-80px -22px;
}

.flag_bn
{
    background-position:-96px -22px;
}

.flag_bo
{
    background-position:-112px -22px;
}

.flag_br
{
    background-position:-128px -22px;
}

.flag_bs
{
    background-position:-144px -22px;
}

.flag_bt
{
    background-position:0px -33px;
}

.flag_bv
{
    background-position:-16px -33px;
}

.flag_bw
{
    background-position:-32px -33px;
}

.flag_by
{
    background-position:-48px -33px;
}

.flag_bz
{
    background-position:-64px -33px;
}

.flag_ca
{
    background-position:-80px -33px;
}

.flag_catalonia
{
    background-position:-96px -33px;
}

.flag_cc
{
    background-position:-112px -33px;
}

.flag_cd
{
    background-position:-128px -33px;
}

.flag_cf
{
    background-position:-144px -33px;
}

.flag_cg
{
    background-position:0px -44px;
}

.flag_ch
{
    background-position:-16px -44px;
}

.flag_ci
{
    background-position:-32px -44px;
}

.flag_ck
{
    background-position:-48px -44px;
}

.flag_cl
{
    background-position:-64px -44px;
}

.flag_cm
{
    background-position:-80px -44px;
}

.flag_cn
{
    background-position:-96px -44px;
}

.flag_co
{
    background-position:-112px -44px;
}

.flag_cr
{
    background-position:-128px -44px;
}

.flag_cs
{
    background-position:-144px -44px;
}

.flag_cu
{
    background-position:0px -55px;
}

.flag_cv
{
    background-position:-16px -55px;
}

.flag_cx
{
    background-position:-32px -55px;
}

.flag_cy
{
    background-position:-48px -55px;
}

.flag_cz
{
    background-position:-64px -55px;
}

.flag_de
{
    background-position:-80px -55px;
}

.flag_dj
{
    background-position:-96px -55px;
}

.flag_dk
{
    background-position:-112px -55px;
}

.flag_dm
{
    background-position:-128px -55px;
}

.flag_do
{
    background-position:-144px -55px;
}

.flag_dz
{
    background-position:0px -66px;
}

.flag_ec
{
    background-position:-16px -66px;
}

.flag_ee
{
    background-position:-32px -66px;
}

.flag_eg
{
    background-position:-48px -66px;
}

.flag_eh
{
    background-position:-64px -66px;
}

.flag_england
{
    background-position:-80px -66px;
}

.flag_er
{
    background-position:-96px -66px;
}

.flag_es
{
    background-position:-112px -66px;
}

.flag_et
{
    background-position:-128px -66px;
}

.flag_europeanunion
{
    background-position:-144px -66px;
}

.flag_fam
{
    background-position:0px -77px;
}

.flag_fi
{
    background-position:-16px -77px;
}

.flag_fj
{
    background-position:-32px -77px;
}

.flag_fk
{
    background-position:-48px -77px;
}

.flag_fm
{
    background-position:-64px -77px;
}

.flag_fo
{
    background-position:-80px -77px;
}

.flag_fr
{
    background-position:-96px -77px;
}

.flag_ga
{
    background-position:-112px -77px;
}

.flag_gb
{
    background-position:-128px -77px;
}

.flag_gd
{
    background-position:-144px -77px;
}

.flag_ge
{
    background-position:0px -88px;
}

.flag_gf
{
    background-position:-16px -88px;
}

.flag_gh
{
    background-position:-32px -88px;
}

.flag_gi
{
    background-position:-48px -88px;
}

.flag_gl
{
    background-position:-64px -88px;
}

.flag_gm
{
    background-position:-80px -88px;
}

.flag_gn
{
    background-position:-96px -88px;
}

.flag_gp
{
    background-position:-112px -88px;
}

.flag_gq
{
    background-position:-128px -88px;
}

.flag_gr
{
    background-position:-144px -88px;
}

.flag_gs
{
    background-position:0px -99px;
}

.flag_gt
{
    background-position:-16px -99px;
}

.flag_gu
{
    background-position:-32px -99px;
}

.flag_gw
{
    background-position:-48px -99px;
}

.flag_gy
{
    background-position:-64px -99px;
}

.flag_hk
{
    background-position:-80px -99px;
}

.flag_hm
{
    background-position:-96px -99px;
}

.flag_hn
{
    background-position:-112px -99px;
}

.flag_hr
{
    background-position:-128px -99px;
}

.flag_ht
{
    background-position:-144px -99px;
}

.flag_hu
{
    background-position:0px -110px;
}

.flag_id
{
    background-position:-16px -110px;
}

.flag_ie
{
    background-position:-32px -110px;
}

.flag_il
{
    background-position:-48px -110px;
}

.flag_in
{
    background-position:-64px -110px;
}

.flag_io
{
    background-position:-80px -110px;
}

.flag_iq
{
    background-position:-96px -110px;
}

.flag_ir
{
    background-position:-112px -110px;
}

.flag_is
{
    background-position:-128px -110px;
}

.flag_it
{
    background-position:-144px -110px;
}

.flag_jm
{
    background-position:0px -121px;
}

.flag_jo
{
    background-position:-16px -121px;
}

.flag_jp
{
    background-position:-32px -121px;
}

.flag_ke
{
    background-position:-48px -121px;
}

.flag_kg
{
    background-position:-64px -121px;
}

.flag_kh
{
    background-position:-80px -121px;
}

.flag_ki
{
    background-position:-96px -121px;
}

.flag_km
{
    background-position:-112px -121px;
}

.flag_kn
{
    background-position:-128px -121px;
}

.flag_kp
{
    background-position:-144px -121px;
}

.flag_kr
{
    background-position:0px -132px;
}

.flag_kw
{
    background-position:-16px -132px;
}

.flag_ky
{
    background-position:-32px -132px;
}

.flag_kz
{
    background-position:-48px -132px;
}

.flag_la
{
    background-position:-64px -132px;
}

.flag_lb
{
    background-position:-80px -132px;
}

.flag_lc
{
    background-position:-96px -132px;
}

.flag_li
{
    background-position:-112px -132px;
}

.flag_lk
{
    background-position:-128px -132px;
}

.flag_lr
{
    background-position:-144px -132px;
}

.flag_ls
{
    background-position:0px -143px;
}

.flag_lt
{
    background-position:-16px -143px;
}

.flag_lu
{
    background-position:-32px -143px;
}

.flag_lv
{
    background-position:-48px -143px;
}

.flag_ly
{
    background-position:-64px -143px;
}

.flag_ma
{
    background-position:-80px -143px;
}

.flag_mc
{
    background-position:-96px -143px;
}

.flag_md
{
    background-position:-112px -143px;
}

.flag_me
{
    background-position:-128px -143px;
}

.flag_mg
{
    background-position:-144px -143px;
}

.flag_mh
{
    background-position:0px -154px;
}

.flag_mk
{
    background-position:-16px -154px;
}

.flag_ml
{
    background-position:-32px -154px;
}

.flag_mm
{
    background-position:-48px -154px;
}

.flag_mn
{
    background-position:-64px -154px;
}

.flag_mo
{
    background-position:-80px -154px;
}

.flag_mp
{
    background-position:-96px -154px;
}

.flag_mq
{
    background-position:-112px -154px;
}

.flag_mr
{
    background-position:-128px -154px;
}

.flag_ms
{
    background-position:-144px -154px;
}

.flag_mt
{
    background-position:0px -165px;
}

.flag_mu
{
    background-position:-16px -165px;
}

.flag_mv
{
    background-position:-32px -165px;
}

.flag_mw
{
    background-position:-48px -165px;
}

.flag_mx
{
    background-position:-64px -165px;
}

.flag_my
{
    background-position:-80px -165px;
}

.flag_mz
{
    background-position:-96px -165px;
}

.flag_na
{
    background-position:-112px -165px;
}

.flag_nc
{
    background-position:-128px -165px;
}

.flag_ne
{
    background-position:-144px -165px;
}

.flag_nf
{
    background-position:0px -176px;
}

.flag_ng
{
    background-position:-16px -176px;
}

.flag_ni
{
    background-position:-32px -176px;
}

.flag_nl
{
    background-position:-48px -176px;
}

.flag_no
{
    background-position:-64px -176px;
}

.flag_np
{
    background-position:-80px -176px;
}

.flag_nr
{
    background-position:-96px -176px;
}

.flag_nu
{
    background-position:-112px -176px;
}

.flag_nz
{
    background-position:-128px -176px;
}

.flag_om
{
    background-position:-144px -176px;
}

.flag_pa
{
    background-position:0px -187px;
}

.flag_pe
{
    background-position:-16px -187px;
}

.flag_pf
{
    background-position:-32px -187px;
}

.flag_pg
{
    background-position:-48px -187px;
}

.flag_ph
{
    background-position:-64px -187px;
}

.flag_pk
{
    background-position:-80px -187px;
}

.flag_pl
{
    background-position:-96px -187px;
}

.flag_pm
{
    background-position:-112px -187px;
}

.flag_pn
{
    background-position:-128px -187px;
}

.flag_pr
{
    background-position:-144px -187px;
}

.flag_ps
{
    background-position:0px -198px;
}

.flag_pt
{
    background-position:-16px -198px;
}

.flag_pw
{
    background-position:-32px -198px;
}

.flag_py
{
    background-position:-48px -198px;
}

.flag_qa
{
    background-position:-64px -198px;
}

.flag_re
{
    background-position:-80px -198px;
}

.flag_ro
{
    background-position:-96px -198px;
}

.flag_rs
{
    background-position:-112px -198px;
}

.flag_ru
{
    background-position:-128px -198px;
}

.flag_rw
{
    background-position:-144px -198px;
}

.flag_sa
{
    background-position:0px -209px;
}

.flag_sb
{
    background-position:-16px -209px;
}

.flag_sc
{
    background-position:-32px -209px;
}

.flag_scotland
{
    background-position:-48px -209px;
}

.flag_sd
{
    background-position:-64px -209px;
}

.flag_se
{
    background-position:-80px -209px;
}

.flag_sg
{
    background-position:-96px -209px;
}

.flag_sh
{
    background-position:-112px -209px;
}

.flag_si
{
    background-position:-128px -209px;
}

.flag_sj
{
    background-position:-144px -209px;
}

.flag_sk
{
    background-position:0px -220px;
}

.flag_sl
{
    background-position:-16px -220px;
}

.flag_sm
{
    background-position:-32px -220px;
}

.flag_sn
{
    background-position:-48px -220px;
}

.flag_so
{
    background-position:-64px -220px;
}

.flag_sr
{
    background-position:-80px -220px;
}

.flag_st
{
    background-position:-96px -220px;
}

.flag_sv
{
    background-position:-112px -220px;
}

.flag_sy
{
    background-position:-128px -220px;
}

.flag_sz
{
    background-position:-144px -220px;
}

.flag_tc
{
    background-position:0px -231px;
}

.flag_td
{
    background-position:-16px -231px;
}

.flag_tf
{
    background-position:-32px -231px;
}

.flag_tg
{
    background-position:-48px -231px;
}

.flag_th
{
    background-position:-64px -231px;
}

.flag_tj
{
    background-position:-80px -231px;
}

.flag_tk
{
    background-position:-96px -231px;
}

.flag_tl
{
    background-position:-112px -231px;
}

.flag_tm
{
    background-position:-128px -231px;
}

.flag_tn
{
    background-position:-144px -231px;
}

.flag_to
{
    background-position:0px -242px;
}

.flag_tr
{
    background-position:-16px -242px;
}

.flag_tt
{
    background-position:-32px -242px;
}

.flag_tv
{
    background-position:-48px -242px;
}

.flag_tw
{
    background-position:-64px -242px;
}

.flag_tz
{
    background-position:-80px -242px;
}

.flag_ua
{
    background-position:-96px -242px;
}

.flag_ug
{
    background-position:-112px -242px;
}

.flag_um
{
    background-position:-128px -242px;
}

.flag_us
{
    background-position:-144px -242px;
}

.flag_uy
{
    background-position:0px -253px;
}

.flag_uz
{
    background-position:-16px -253px;
}

.flag_va
{
    background-position:-32px -253px;
}

.flag_vc
{
    background-position:-48px -253px;
}

.flag_ve
{
    background-position:-64px -253px;
}

.flag_vg
{
    background-position:-80px -253px;
}

.flag_vi
{
    background-position:-96px -253px;
}

.flag_vn
{
    background-position:-112px -253px;
}

.flag_vu
{
    background-position:-128px -253px;
}

.flag_wales
{
    background-position:-144px -253px;
}

.flag_wf
{
    background-position:0px -264px;
}

.flag_ws
{
    background-position:-16px -264px;
}

.flag_ye
{
    background-position:-32px -264px;
}

.flag_yt
{
    background-position:-48px -264px;
}

.flag_za
{
    background-position:-64px -264px;
}

.flag_zm
{
    background-position:-80px -264px;
}

.flag_zw
{
    background-position:-96px -264px;
}

.flag_empty
{
    background-position:-112px -264px;
}
</style>

<div id="content">
    <div id="mcontent">
        <!-- google fonts-->
        <div class="googlefonts">Test van google fonts open sans</div>


        <!--knop die schaalt als de text grote wordt -->
        <a onclick="this.blur(); return false;" href="#" class="button"><span>Save grote text</span></a>
        <a onclick="this.blur(); return false;" href="#" class="button"><span>Cancel</span></a>


        <!------------flags ------------------>

        <div class="flag_nl flagicon"></div>


    </div>
</div>

