<div id="content">
    <div id="mcontent">
        <!-- Defining Header for content section -->
        <header>
            <h2>About US</h2>
        </header>
        <!-- Defining Content Section -->
        <section>
            <!-- Defining content section article -->
            <article class="bpage">
                <div>
                    <?php echo $this->form ?>
                </div>
                <div class="image">
                </div>
            </article>
        </section>
    </div>
    <!-- Defining Sidebar / Aside -->
    <aside>
        <section>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Feedback</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </section>
        <section>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Feedback</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </section>
        <section>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Feedback</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </section>
    </aside>
</div>

