<link href="/css/dataTable.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery.dataTable.js"></script>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    $('#example').dataTable();
} );
</script>



<div id="content">
    <div id="mcontent">
<div class="rates">
<br/>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
    <thead>
        <tr>
            <th>Land</th>
            <th>Landnummer</th>
            <th>Prijs per pagina</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>10.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>

        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>

        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>
        <tr class="odd gradeX">
            <td>landnaam</td>
            <td>landnr</td>
            <td>00.1000</td>
        </tr>


    </tbody>
    <tfoot>
        <tr>
            <th>Land</th>
            <th>Landnummer</th>
            <th>Prijs per pagina</th>
        </tr>
    </tfoot>
</table>
<br/>
</div>

    </div>
</div>

