      <link href="/uploadify/uploadify.css" type="text/css" rel="stylesheet" />
      <script type="text/javascript" src="/uploadify/jquery-1.4.2.min.js"></script>
      <script type="text/javascript" src="/uploadify/swfobject.js"></script>
      <script type="text/javascript" src="/uploadify/jquery.uploadify.v2.1.4.min.js"></script>
      <?php if(is_dir("/data/uploads")) exit();?>
      <script type="text/javascript">
      $(document).ready(function() {
        $('#file_upload').uploadify({
         'uploader'  : '/uploadify/uploadify.swf',
          'script'    : '/uploadify/uploadify.php',
          'cancelImg' : '/uploadify/cancel.png',
          'folder'    : '/uploads',
          'auto'      : true,
          
          'buttonText'  : 'Add to Queue!',
          'buttonImg'   : '/uploadify/button.jpg',
          'displayData' : 'percentage',
          'expressInstall' : '/uploadify/expressInstall.swf',
          'fileExt'     : '*.jpg;*.gif;*.png',
          'fileDesc'    : 'Image Files',
          'method'      : 'post',
          'multi'       : true,
          'removeCompleted' : false
        });
      });
      </script>


uploadify
<input id="file_upload" name="file_upload" type="file" />